name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify the Node.js versions you want to test with

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enables caching for faster builds

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint # if you have lint script

      - name: Build project
        run: npm run build # Assuming you have a build script in package.json
  
  docker:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after build
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . firstAssignment
        
      - name: Run Docker container
        run: docker run -d --name firstAssignment -p 5173:5173 firstAssignment
