name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify the Node.js versions you want to test with

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enables caching for faster builds

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint # if you have lint script

      - name: Build project
        run: npm run build # Assuming you have a build script in package.json
  
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t first-assignment .

    - name: Create and run container
      run: |
        docker create --name first-assignment-container first-assignment
        docker start first-assignment-container
        docker ps
        docker stop first-assignment-container
